unpackaged-source/main/default/objects/Contact/recordTypes/BlueWave_Customer.recordType-meta.xml
<RecordType>
    <fullName>BlueWave_Customer</fullName>
    <active>true</active>
    <description>Record Type for BlueWave Solar solution</description>
    <label>BlueWave Customer</label>
</RecordType>

unpackaged-source/main/default/objects/Shared_Solar_System__c/Shared_Solar_System__c.object-meta.xml
<CustomObject>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged-source/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged-source/main/default/objects/Subscription__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Before trigger controls this field.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged-source/main/default/objects/Subscription__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged-source/main/default/objects/Subscription__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Date the subscription ends</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged-source/main/default/objects/Subscription__c/fields/Shared_Solar_System__c.field-meta.xml
<CustomField>
    <fullName>Shared_Solar_System__c</fullName>
    <label>Shared Solar System</label>
    <referenceTo>Shared_Solar_System__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged-source/main/default/objects/Subscription__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Date the subscription begins</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged-source/main/default/classes/TriggerTest_Subscription.cls
@isTest
public class TriggerTest_Subscription {
    
    public static Id customerRecId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('BlueWave_Customer').getRecordTypeId();
    
    @testSetup 
    static void testSetup() {
        
        List<Contact> customers = new List<Contact>();
        
        Contact customer1 = new Contact(FirstName = 'Test1', LastName = 'Customer1', RecordTypeId = customerRecId);
        customers.add(customer1);
        
        insert customers;
        
        List<Shared_Solar_System__c> solarSystems = new List<Shared_Solar_System__c>();
        
        Shared_Solar_System__c system1 = new Shared_Solar_System__c(Name = 'Solar System 1 Trigger Test');
        solarSystems.add(system1);
        
        insert solarSystems;
        
        List<Subscription__c> subscriptions = new List<Subscription__c>();
        
        Subscription__c sub1 = new Subscription__c(Customer__c = customer1.Id, Shared_Solar_System__c = system1.Id, 
                                                   Start_Date__c = date.today(), End_Date__c = date.today().addDays(10));
        
        subscriptions.add(sub1);
        
        Subscription__c sub2 = new Subscription__c(Customer__c = customer1.Id, Shared_Solar_System__c = system1.Id, 
                                                   Start_Date__c = date.today().addDays(30), End_Date__c = date.today().addDays(40));
        
        subscriptions.add(sub2);
        
        insert subscriptions;      
        
    }
    
    @isTest
    public static void isSubscriptionActiveTest() {
        List<Subscription__c> subs = [SELECT Id, Start_Date__c, End_Date__c, Active__c FROM Subscription__c ORDER BY Start_Date__c];
        System.assertEquals(subs[0].Active__c, true);
        System.assertEquals(subs[1].Active__c, false);
    }
    
    @isTest
    public static void checkForOverlappingDatesTest() {
        Id contactId = [SELECT Id FROM Contact LIMIT 1].Id;
        Id solarSystemId = [SELECT Id FROM Shared_Solar_System__c LIMIT 1].Id;
        
        try {
            Subscription__c overlappingSub = new Subscription__c(Customer__c = contactId, Shared_Solar_System__c = solarSystemId, 
                                                   Start_Date__c = date.today(), End_Date__c = date.today().addDays(30));
            
            insert overlappingSub;
            
        } catch(Exception e) {
            Boolean expectedExceptionThrown = e.getMessage().contains('Customer can not have overlapping dates for the same solar system.') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);            
        }
        
    }
}